//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPiggyBank.Core.Communication.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyPiggyBank.Core.Communication.Account.AccountResources", typeof(AccountResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        public static string AccountService_Authenticate_Password_Incorrect {
            get {
                return ResourceManager.GetString("AccountService_Authenticate_Password_Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string AccountService_Authenticate_User_NotFound {
            get {
                return ResourceManager.GetString("AccountService_Authenticate_User_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail is already being used..
        /// </summary>
        public static string AccountService_Register_Email_Exists_Error {
            get {
                return ResourceManager.GetString("AccountService_Register_Email_Exists_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this name already exists..
        /// </summary>
        public static string AccountService_Register_Username_Exists_Error {
            get {
                return ResourceManager.GetString("AccountService_Register_Username_Exists_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address is required..
        /// </summary>
        public static string LoginRequestValidator_Email_Empty_Error {
            get {
                return ResourceManager.GetString("LoginRequestValidator_Email_Empty_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid e-mail is required..
        /// </summary>
        public static string LoginRequestValidator_Email_NotValid_Error {
            get {
                return ResourceManager.GetString("LoginRequestValidator_Email_NotValid_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string LoginRequestValidator_Password_Empty_Error {
            get {
                return ResourceManager.GetString("LoginRequestValidator_Password_Empty_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address is required..
        /// </summary>
        public static string RegisterRequestValidator_Email_Empty_Error {
            get {
                return ResourceManager.GetString("RegisterRequestValidator_Email_Empty_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid e-mail is required..
        /// </summary>
        public static string RegisterRequestValidator_Email_NotValid_Error {
            get {
                return ResourceManager.GetString("RegisterRequestValidator_Email_NotValid_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one digit..
        /// </summary>
        public static string RegisterRequestValidator_Password_Digit_Error {
            get {
                return ResourceManager.GetString("RegisterRequestValidator_Password_Digit_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string RegisterRequestValidator_Password_Empty_Error {
            get {
                return ResourceManager.GetString("RegisterRequestValidator_Password_Empty_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least 8 letters..
        /// </summary>
        public static string RegisterRequestValidator_Password_Length_Error {
            get {
                return ResourceManager.GetString("RegisterRequestValidator_Password_Length_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one special character..
        /// </summary>
        public static string RegisterRequestValidator_Password_SpecialCharacter_Error {
            get {
                return ResourceManager.GetString("RegisterRequestValidator_Password_SpecialCharacter_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one upper case letter..
        /// </summary>
        public static string RegisterRequestValidator_Password_UpperCaseLetter_Error {
            get {
                return ResourceManager.GetString("RegisterRequestValidator_Password_UpperCaseLetter_Error", resourceCulture);
            }
        }
    }
}
